package sercos.gui;

import sercos.gui.event.EventUtils;

import javax.swing.*;

/**
 * Created by 宗祥 on 2017/2/27.
 */
public class MainFrame extends JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        toolPanel = new JPanel();
        jToolBar1 = new JToolBar();
        simulationBtn = new JButton();
        analysisBtn = new JButton();
        mainPanel = new JPanel();
        analysisResultPanel = new JPanel();
        jPanel2 = new JPanel();
        analysisResultSPanel = new JScrollPane();
        analysisResultTable = new AnalysisResultTable();
        analysisResultDetailPanel = new JPanel();
        detailTreeSP = new JScrollPane();
        detailTree = new JTree();
        binaryPanel = new JScrollPane();
        simMapPanel = new JPanel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new BoxLayout(getContentPane(), BoxLayout.Y_AXIS));

        toolPanel.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        simulationBtn.setText("仿真");
        simulationBtn.setBorder(BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        simulationBtn.setFocusable(false);
        simulationBtn.setHorizontalTextPosition(SwingConstants.CENTER);
        simulationBtn.setVerticalTextPosition(SwingConstants.BOTTOM);
        jToolBar1.add(simulationBtn);

        analysisBtn.setText("分析");
        analysisBtn.setBorder(BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        analysisBtn.setFocusable(false);
        analysisBtn.setHorizontalTextPosition(SwingConstants.CENTER);
        analysisBtn.setVerticalTextPosition(SwingConstants.BOTTOM);
        jToolBar1.add(analysisBtn);

        toolPanel.add(jToolBar1, java.awt.BorderLayout.CENTER);

        getContentPane().add(toolPanel);

        mainPanel.setLayout(new java.awt.GridLayout(1, 0));

        analysisResultPanel.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBorder(BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
        analysisResultSPanel.setViewportView(analysisResultTable);

        jPanel2.add(analysisResultSPanel);

        analysisResultDetailPanel.setLayout(new BoxLayout(analysisResultDetailPanel, BoxLayout.X_AXIS));

        detailTreeSP.setViewportView(detailTree);

        analysisResultDetailPanel.add(detailTreeSP);

        binaryPanel.setBorder(BorderFactory.createEtchedBorder());
        analysisResultDetailPanel.add(binaryPanel);

        jPanel2.add(analysisResultDetailPanel);

        //注册事件
        EventUtils.listenerSimulationBtn(simulationBtn);
        EventUtils.listenerAnalysisBtn(analysisBtn, analysisResultTable);
        EventUtils.listenerTableToDetailTree(analysisResultTable, detailTree);

        analysisResultPanel.add(jPanel2);

        mainPanel.add(analysisResultPanel);

        simMapPanel.setBorder(BorderFactory.createEtchedBorder());

        GroupLayout simMapPanelLayout = new GroupLayout(simMapPanel);
        simMapPanel.setLayout(simMapPanelLayout);
        simMapPanelLayout.setHorizontalGroup(
                simMapPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 800, Short.MAX_VALUE)
        );
        simMapPanelLayout.setVerticalGroup(
                simMapPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 609, Short.MAX_VALUE)
        );

        mainPanel.add(simMapPanel);

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mainFrame = new MainFrame();
                mainFrame.setTitle("Sercos 仿真分析");
                mainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private JButton analysisBtn;
    private JPanel analysisResultDetailPanel;
    private JPanel analysisResultPanel;
    private JScrollPane analysisResultSPanel;
    private JScrollPane binaryPanel;
    private JTree detailTree;
    private JScrollPane detailTreeSP;
    private JPanel jPanel2;
    private AnalysisResultTable analysisResultTable;
    private JToolBar jToolBar1;
    private JPanel mainPanel;
    private JPanel simMapPanel;
    private JButton simulationBtn;
    private JPanel toolPanel;
    // End of variables declaration
}
